(define (triangle row col)
  (cond ((= col 1) 1)
        ((or (< col 1) (< row col)) 0)
        (else (+ (triangle (- row 1) (- col 1))
                 (triangle (- row 1) col)))))
(triangle 1 1)
(triangle 1 2)
(triangle 1 3)
(triangle 1 4)
(triangle 2 1)
(triangle 2 2)
(triangle 2 3)
(triangle 2 4)
(triangle 3 1)
(triangle 3 2)
(triangle 3 3)
(triangle 3 4)
(triangle 4 1)
(triangle 4 2)
(triangle 4 3)
(triangle 4 4)
