(define (lmultiply a b)
  (define (lm a b acc) 
    (cond ((= b 0) acc)
          ((even? b) (lm (double a) (halve b) acc))
          (else (lm a (- b 1) (+ acc a)))))
  (lm a b 0))
(define (double n)
  (+ n n))
(define (halve n)
  (/ n 2))
(lmultiply 0 100)
(lmultiply 100 0)
(lmultiply 1 20)
(lmultiply 20 1)
(lmultiply 13 100)
(lmultiply 14 100)
(lmultiply 13 101)
(lmultiply 14 101)
