(define (timed-prime-test n)
  (newline)
  (display n)
  (start-prime-test n (runtime)))
(define (start-prime-test n start-time)
  (if (prime? n)
      (report-prime (- (runtime) start-time))))
(define (report-prime elapsed-time)
  (display " *** ")
  (display elapsed-time))
(define (search-for-primes n)
  (define (sfp n cnt)
    (cond ((= cnt 0) (display "Done"))
          ((prime? n) ((timed-prime-test n) (sfp (+ 1 n) (- cnt 1))))
          (sfp (+ 1 n) cnt)))
  (sfp n 3))
(search-for-primes 1000)  
(search-for-primes 10000)  
(search-for-primes 100000)  
